[tool.black]
line-length = 88
skip-string-normalization = true

[tool.coverage.run]
command_line = "-m pytest"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.pylint.'MESSAGES CONTROL']
disable = """bad-continuation,
          bad-whitespace,
          invalid-name,
          logging-fstring-interpolation
          """
