[units.defaults]

acceleration = "m / s ** 2"
angle = "radian"
angular_momentum = "kg * m ** 2 / s"
angular_momentum_specific = "m ** 2 / s"
density = "kg / m ** 3"
energy = "joule"
energy_specific = "joule / kg"
entropy = "joule / kelvin"
force = "newton"
frequency = "hertz"
length = "m"
magnetic_field = "tesla"
mass = "kg"
momentum = "kg * m / s"
power = "watt"
pressure = "pascal"
temperature = "kelvin"
time = "s"
velocity = "m / s"

[units.definitions]

solar_mass = "1.9891e30 kg"
solar_radius = "6.959500e8 m"
earth_mass = "5.979e24 kg"
earth_radius = "6.371315e6 m"
jupiter_mass = "1.89813e27 kg"

[arrays.dimensions]

accretion_radius = "length: 1"
alpha_viscosity_numerical = ""
ambipolar_diffusion_coefficient = "length: 2, time: -1"
angular_momentum = "mass: 1, length: 2, time: -1"
angular_velocity = "time: -1"
azimuthal_angle = "angle: 1"
density = "mass: 1, length: -3"
differential_velocity = "length: 1, time: -1"
dust_density = "mass: 1, length: -3"
dust_fraction = ""
dust_mass = "mass: 1"
dust_to_gas_ratio = ""
eccentricity = ""
electron_fraction = ""
gas_density = "mass: 1, length: -3"
gas_fraction = ""
gas_mass = "mass: 1"
gravitational_potential = "mass: 1, length: 2, time: -2"
grain_density = "mass: 1, length: -3"
grain_size = "length: 1"
hall_effect_coefficient = "length: 2, time: -1"
id = ""
inclination = "angle: 1"
internal_energy = "mass: 1, length: 2, time: -2"
keplerian_frequency = "time: -1"
kinetic_energy = "mass: 1, length: 2, time: -2"
last_injection_time = "time: 1"
luminosity = "mass: 1, length: 2, time: -3"
magnetic_field = "mass: 1, time: -2, current: -1"
magnetic_field_curl = "mass: 1, time: -2, current: -1, length: -1"
magnetic_field_divergence = "mass: 1, time: -2, current: -1, length: -1"
magnetic_field_psi = "mass: 1, time: -3, current: -1, length: 1"
mass = "mass: 1"
mass_accreted = "mass: 1"
mass_loss_rate = "mass: 1, time: -1"
momentum = "mass: 1, length: 1, time: -1"
ohmic_resistivity_coefficient = "length: 2, time: -1"
polar_angle = "angle: 1"
position = "length: 1"
pressure = "mass: 1, length: -1, time: -2"
projection = "length: 1"
radius_cylindrical = "length: 1"
radius_effective = "length: 1"
radius_spherical = "length: 1"
relative_on_fragmentation_velocity = ""
semi_major_axis = "length: 1"
smoothing_length = "length: 1"
softening_radius = "length: 1"
sound_speed = "length: 1, time: -1"
specific_angular_momentum = "length: 2, time: -1"
specific_internal_energy = "length: 2, time: -2"
specific_kinetic_energy = "length: 2, time: -2"
spin = "mass: 1, length: 2, time: -1"
stokes_number = ""
stopping_time = "time: 1"
sub_type = ""
temperature = "temperature: 1"
temperature_dust = "temperature: 1"
temperature_effective = "temperature: 1"
timestep = "time: 1"
type = ""
velocity = "length: 1, time: -1"
velocity_divergence = "time: -1"
velocity_radial_cylindrical = "length: 1, time: -1"
velocity_radial_spherical = "length: 1, time: -1"
vorticity = "time: -1"

[arrays.aliases]

angular_momentum = "L"
angular_velocity = "v_phi"
azimuthal_angle = "phi"
density = "rho"
dust_density = "rho_d"
dust_fraction = "eps"
eccentricity = "e"
gas_density = "rho_g"
keplerian_frequency = "omega_k"
magnetic_field = "B"
mass = "m"
mass_loss_rate = "mdot"
momentum = "p"
polar_angle = "theta"
position = "pos"
pressure = "P"
radius_cylindrical = "R"
radius_spherical = "r"
smoothing_length = "h"
sound_speed = "c_s"
specific_angular_momentum = "j"
specific_internal_energy = "u"
stokes_number = "St"
stopping_time = "t_s"
temperature = "T"
timestep = "dt"
velocity = "v"
velocity_radial_cylindrical = "v_R"
velocity_radial_spherical = "v_r"

[phantom.particles.namemap]

abundance = "abundance"
alpha = "alpha_viscosity_numerical"
Bxyz = "magnetic_field"
curlBxyz = "magnetic_field_curl"
curlvxyz = "vorticity"
deltavxyz = "differential_velocity"
divB = "magnetic_field_divergence"
divv = "velocity_divergence"
dt = "timestep"
dustfrac = "dust_fraction"
eta_AD = "ambipolar_diffusion_coefficient"
eta_HE = "hall_effect_coefficient"
eta_OR = "ohmic_resistivity_coefficient"
gr_density = "density_general_relativity"
gr_entropy = "entropy_general_relativity"
gr_momentum = "momentum_general_relativity"
graindens = "grain_density"
grainsize = "grain_size"
h = "smoothing_length"
itype = "type"
luminosity = "luminosity"
ne_on_n = "electron_fraction"
poten = "gravitational_potential"
pressure = "pressure"
psi = "magnetic_field_psi"
St = "stokes_number"
T = "temperature"
temperature_dust = "temperature_dust"
tstop = "stopping_time"
u = "specific_internal_energy"
vrel_on_vfrag = "relative_on_fragmentation_velocity"
vxyz = "velocity"
xyz = "position"

[phantom.sinks.namemap]

h = "accretion_radius"
hsoft = "softening_radius"
lum = "luminosity"
m = "mass"
maccreted = "mass_accreted"
mdotloss = "mass_loss_rate"
Reff = "radius_effective"
spinxyz = "spin"
Teff = "temperature_effective"
tlast = "last_injection_time"
vxyz = "velocity"
xyz = "position"

[phantom.time_series.namemap]

"B ave" = "magnetic_field_average"
"B max" = "magnetic_field_max"
"B min" = "magnetic_field_min"
alpha = "alpha_viscosity_numerical"
angtot = "angular_momentum"
"beta_P ave" = "plasma_beta_average"
"beta_P max" = "plasma_beta_max"
"beta_P min" = "plasma_beta_min"
"divB ave" = "magnetic_field_divergence_average"
"divB max" = "magnetic_field_divergence_max"
dt = "timestep"
dtmax = "timestep_max"
"dust/gas" = "dust_gas_ratio"
ekin = "energy_kinetic"
emag = "energy_magnetic"
epot = "energy_potential"
erot = "energy_rotational_total"
erot_x = "energy_rotational_x"
erot_y = "energy_rotational_y"
erot_z = "energy_rotational_z"
etherm = "energy_thermal"
etot = "energy_total"
fssx = "sink_sink_force_x"
fssy = "sink_sink_force_y"
fssz = "sink_sink_force_z"
fx = "force_x"
fy = "force_y"
fz = "force_z"
macc = "mass_accreted"
"rho ave" = "density_average"
"rho bdy ave" = "boundary_density_average"
"rho bdy max" = "boundary_density_max"
"rho blg ave" = "bulge_density_average"
"rho blg max" = "bulge_density_max"
"rho dm ave" = "dark_matter_density_average"
"rho dm max" = "dark_matter_density_max"
"rho dust A" = "dust_density_average"
"rho dust X" = "dust_density_max"
"rho gas ave" = "gas_density_average"
"rho gas max" = "gas_density_max"
"rho max" = "density_max"
"rho star A" = "star_density_average"
"rho star X" = "star_density_max"
rmsmach = "mach_number_rms"
spinx = "spin_x"
spiny = "spin_y"
spinz = "spin_z"
t_s = "stopping_time"
time = "time"
totentrop = "entropy"
totmom = "momentum"
vrms = "velocity_rms"
vx = "velocity_x"
vy = "velocity_y"
vz = "velocity_z"
x = "position_x"
xcom = "center_of_mass_x"
y = "position_y"
ycom = "center_of_mass_y"
z = "position_z"
zcom = "center_of_mass_z"

[phantom.time_series.dimensions]
alpha_viscosity_numerical = ""
angular_momentum = "mass: 1, length: 2, time: -1"
boundary_density_average = "mass: 1, length: -3"
boundary_density_max = "mass: 1, length: -3"
bulge_density_average = "mass: 1, length: -3"
bulge_density_max = "mass: 1, length: -3"
center_of_mass_x = "length: 1"
center_of_mass_y = "length: 1"
center_of_mass_z = "length: 1"
dark_matter_density_average = "mass: 1, length: -3"
dark_matter_density_max = "mass: 1, length: -3"
density_average = "mass: 1, length: -3"
density_max = "mass: 1, length: -3"
dust_density_average = "mass: 1, length: -3"
dust_density_max = "mass: 1, length: -3"
dust_gas_ratio = ""
energy_kinetic = "mass: 1, length: 2, time: -2"
energy_magnetic = "mass: 1, length: 2, time: -2"
energy_potential = "mass: 1, length: 2, time: -2"
energy_rotational_total = "mass: 1, length: 2, time: -2"
energy_rotational_x = "mass: 1, length: 2, time: -2"
energy_rotational_y = "mass: 1, length: 2, time: -2"
energy_rotational_z = "mass: 1, length: 2, time: -2"
energy_thermal = "mass: 1, length: 2, time: -2"
energy_total = "mass: 1, length: 2, time: -2"
entropy = "mass: 1, length: 2, time: -2, temperature: -1"
force_x = "mass: 1, length: 1, time: -2"
force_y = "mass: 1, length: 1, time: -2"
force_z = "mass: 1, length: 1, time: -2"
gas_density_average = "mass: 1, length: -3"
gas_density_max = "mass: 1, length: -3"
mach_number_rms = ""
magnetic_field_average = "mass: 1, time: -2, current: -1"
magnetic_field_divergence_average = "mass: 1, time: -2, current: -1"
magnetic_field_divergence_max = "mass: 1, time: -2, current: -1"
magnetic_field_max = "mass: 1, time: -2, current: -1"
magnetic_field_min = "mass: 1, time: -2, current: -1"
mass_accreted = "mass: 1"
momentum = "mass: 1, length: 1, time: -1"
plasma_beta_average = ""
plasma_beta_max = ""
plasma_beta_min = ""
position_x = "length: 1"
position_y = "length: 1"
position_z = "length: 1"
sink_sink_force_x = "mass: 1, length: 1, time: -2"
sink_sink_force_y = "mass: 1, length: 1, time: -2"
sink_sink_force_z = "mass: 1, length: 1, time: -2"
spin_x = "mass: 1, length: 2, time: -1"
spin_y = "mass: 1, length: 2, time: -1"
spin_z = "mass: 1, length: 2, time: -1"
star_density_average = "mass: 1, length: -3"
star_density_max = "mass: 1, length: -3"
stopping_time = "time: 1"
time = "time: 1"
timestep = "time: 1"
timestep_max = "time: 1"
velocity_rms = "length: 1, time: -1"
velocity_x = "length: 1, time: -1"
velocity_y = "length: 1, time: -1"
velocity_z = "length: 1, time: -1"
